name: Bump Base Container Version

on:
  schedule:
    - cron: '17 4 * * 2'
  repository_dispatch:
    types: [bump]

jobs:
  bump_docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: bump base version
        run: bash bump_docker_base.sh
        env:
          REPO_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          REPO_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: EndBug/add-and-commit@v4
        with:
          add: 'Dockerfile'
          author_name: 'Github version bumperator'
          author_email: 'wiha1292@colorado.edu'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump_pipenv:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: install pipenv
        run: python3 -m pip install pipenv

      - name: update dependencies
        run: python3 -m pipenv update

      - name: lock dependencies
        run: python3 -m pipenv lock

      - uses: EndBug/add-and-commit@v4
        with:
          add: 'Pipfile.lock'
          author_name: 'Github pipenv bumperator'
          author_email: 'wiha1292@colorado.edu'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
